// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Debug","status":true,"description":"","parameters":{}},
{"name":"OuterWindow","status":true,"description":"aa","parameters":{"windowPath":"subWindow"}}
];
