// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OuterWindow","status":true,"description":"画面外演出をするためにサブウィンドウを表示するプラグイン","parameters":{"windowPath":"subWindow"}},
{"name":"Debug","status":true,"description":"タイトル画面ぶっ飛ばして、デベロッパーツールをデフォで出すやつ","parameters":{"needDeveloperTool":"false"}}
];
